# Here the docstrings are generated by ChatGPT (instant)
import random
from value import Value


class Neuron:
    """
    Represents a single artificial neuron.

    A neuron consists of:
    - one trainable weight for each input feature
    - one trainable bias

    During the forward pass, it computes:
        output = tanh(w₁x₁ + w₂x₂ + ... + wₙxₙ + b)

    where the weights and bias are learned during training.
    """


    def __init__(self, n_inputs):
        """
        Initialize the neuron.

        Creates one randomly initialized weight for each input
        feature and initializes the bias to zero.

        Args:
            n_inputs:   Number of input features connected to
                        this neuron.
        """
        self.w = [Value(data=random.uniform(-1, 1)) for _ in range(n_inputs)]
        self.b = Value(0.0)


    def __call__(self, x):
        """
        Compute the neuron's output for a given input.

        The weighted sum is computed as:
            activation = w₁x₁ + w₂x₂ + ... + wₙxₙ + b

        The hyperbolic tangent activation function is then
        applied to introduce non-linearity.

        Args:
            x: Iterable containing the input values.

        Returns:
            A Value object representing the neuron's output.
        """
        act = sum((wi * xi for wi, xi in zip(self.w, x)), self.b)
        return act.tanh()


    def parameters(self):
        """
        Return all trainable parameters of the neuron.

        Returns:
            A list containing every weight followed by the bias.
            These parameters are optimized during training.
        """
        return self.w + [self.b]