# Here the docstrings are generated by ChatGPT (instant)
import random
from value import Value
from visualise import draw_dot


class Neuron:
    """
    Represents a single artificial neuron.

    A neuron consists of:
    - one trainable weight for each input feature
    - one trainable bias

    During the forward pass, it computes:
        output = tanh(w₁x₁ + w₂x₂ + ... + wₙxₙ + b)

    where the weights and bias are learned during training.
    """


    def __init__(self, n_inputs):
        """
        Initialize the neuron.

        Creates one randomly initialized weight for each input
        feature and initializes the bias to zero.

        Args:
            n_inputs:   Number of input features connected to
                        this neuron.
        """
        self.w = [Value(data=random.uniform(-1, 1)) for _ in range(n_inputs)]
        self.b = Value(0.0)


    def __call__(self, x):
        """
        Compute the neuron's output for a given input.

        The weighted sum is computed as:
            activation = w₁x₁ + w₂x₂ + ... + wₙxₙ + b

        The hyperbolic tangent activation function is then
        applied to introduce non-linearity.

        Args:
            x: Iterable containing the input values.

        Returns:
            A Value object representing the neuron's output.
        """
        act = sum((wi * xi for wi, xi in zip(self.w, x)), self.b)
        return act.tanh()


    def parameters(self):
        """
        Return all trainable parameters of the neuron.

        Returns:
            A list containing every weight followed by the bias.
            These parameters are optimized during training.
        """
        return self.w + [self.b]


class Layer:
    """
    Represents a fully connected neural network layer.

    A layer is a collection of neurons that all receive the same
    input vector. Each neuron independently computes its output,
    producing one element of the layer's output.
    """

    def __init__(self, n_inputs, n_outputs):
        """
        Initialize the layer.

        Creates the specified number of neurons, where each neuron
        is connected to every input feature.

        Args:
            n_inputs: Number of input features received by each
                neuron.
            n_outputs: Number of neurons in the layer.
        """
        self.neurons = [Neuron(n_inputs) for _ in range(n_outputs)]

    def __call__(self, x):
        """
        Perform a forward pass through the layer.

        Each neuron receives the same input vector and computes its
        own output.

        Args:
            x: Iterable containing the input values.

        Returns:
            A list of Value objects, one for each neuron in the
            layer.
        """
        return [neuron(x) for neuron in self.neurons]

    def parameters(self):
        """
        Return all trainable parameters in the layer.

        Collects the parameters from every neuron and flattens them
        into a single list.

        Returns:
            A list containing every weight and bias in the layer.
        """
        return [parameter for neuron in self.neurons for parameter in neuron.parameters()]


class MLP:
    """
    Represents a Multi-Layer Perceptron (MLP).

    An MLP is a feedforward neural network composed of one or more
    fully connected layers. The output of each layer becomes the
    input to the next layer.

    The network architecture is defined by a list of layer sizes.
    For example:
        sizes = [3, 4, 4, 1]

    creates:
        - 3 input features
        - first hidden layer with 4 neurons
        - second hidden layer with 4 neurons
        - output layer with 1 neuron
    """

    def __init__(self, n_inputs, n_outputs):
        """
        Initialize the neural network.

        Consecutive values in `sizes` define the input and output
        dimensions of each layer.

        Args:
            sizes: List of integers describing the network
                architecture.
        """
        sizes = [n_inputs] + n_outputs
        self.layers = [Layer(sizes[i], sizes[i + 1]) for i in range(len(sizes) - 1)]

    def __call__(self, x):
        """
        Perform a forward pass through the network.

        The input is passed sequentially through every layer.

        Args:
            x: Iterable containing the input features.

        Returns:
            The network output.

            If the output layer contains one neuron, a single
            Value object is returned. Otherwise, a list of Value
            objects is returned.
        """
        for layer in self.layers:
            x = layer(x)

        return x[0] if len(x) == 1 else x

    def parameters(self):
        """
        Return all trainable parameters in the network.

        Collects the parameters from every layer and flattens them
        into a single list.

        Returns:
            A list containing every weight and bias in the MLP.
        """
        return [parameter for layer in self.layers for parameter in layer.parameters()]

print("-"*40)
print("CLASS: Neuron")
print("-"*40)
x_neuron = [1.0, 2.0]
neuron = Neuron(2)
print(neuron(x_neuron))
print()

print("-"*40)
print("CLASS: Layer")
print("-"*40)
x_layer = [1.0, 2.0]
layer = Layer(2, 3)
print(layer(x_layer))
print()

print("-"*40)
print("CLASS: MLP")
print("-"*40)
x = [1.0, 2.0, 3.0]
mlp = MLP(3, [4, 4, 1])
print(mlp(x))
print()

print("-"*40)
print("Parameters")
print("-"*40)
print(mlp.parameters())

dot = draw_dot(root=mlp(x=x))
dot.render("graph_nn", cleanup=True)

print("-"*40)
print("Using the nn.py")
print("-"*40)
xs = [
    [2.0, 3.0, -1.0],
    [3.0, -1.0, 0.5],
    [0.5, 1.0, 1.0],
    [1.0, 1,0, -1.0],
]
ys = [1.0, -1.0, 1.0, 1.0] # desired outputs

for k in range(20):
    # Forward pass
    y_pred = [mlp(x) for x in xs]
    loss = sum([(y_out - y_gt) ** 2 for y_gt, y_out in zip(ys, y_pred)])

    # grad=0
    for p in mlp.parameters():
        p.grad = 0 

    # backward pass
    loss.backward()

    # update
    for p in mlp.parameters():
        p.data += -0.05 * p.grad 

    print(k, loss.data)
# print("gradient of a neuron")
# print(mlp.layers[0].neurons[0].w[0].grad)
# print("value of a neuron")
# print(mlp.layers[0].neurons[0].w[0].data)

dot = draw_dot(root=loss)
dot.render("graph_nn_loss", cleanup=True)
