# Here the docstrings are generated by ChatGPT (instant)
class Value:
    """
    Scalar value in a computation graph.

    Each Value stores:
    - data: the numeric value
    - grad: gradient of the final output with respect to this value
    - _backward: function used to propagate gradients to parents
    - _prev: parent nodes that produced this value
    """


    def __init__(self, data, children=(), op=''):
        """
        Initialize a Value node.

        Args:
            data: Numeric value stored in the node.
            children: Parent nodes used to create this value.
            op: Operation that produced this node (e.g. '+', '*').
        """
        self.data = data
        self.grad = 0.0
        self._backward = lambda: None
        self._prev = set(children)
        self._op = op


    def __repr__(self):
        """
        Return a readable string representation of the node.

        Useful for debugging and inspecting values and gradients.
        """
        return f"Value(data={self.data:.4f}, grad={self.grad:.4f})"


    def __add__(self, other):
        """
        Add two Value objects.

        Creates a new node representing:
            output = self + other

        Stores a backward function that propagates gradients
        according to:

            d(output)/d(self)  = 1
            d(output)/d(other) = 1
        """
        other = other if isinstance(other, Value) else Value(other)
        output = Value(
            data=self.data + other.data, 
            children=(self, other), 
            op="+"
            )

        def _backward():
            self.grad += output.grad
            other.grad += output.grad

        output._backward = _backward
        return output


    def __mul__(self, other):
        """
        Multiply two Value objects.

        Creates a new node representing:
            output = self * other

        Stores a backward function that propagates gradients
        using the product rule:

            d(output)/d(self)  = other.data
            d(output)/d(other) = self.data
        """
        other = other if isinstance(other, Value) else Value(other)
        output = Value(
            data=self.data * other.data,
            children=(self, other),
            op="*"
            )

        def _backward():
            self.grad += other.data * output.grad
            other.grad += self.data * output.grad

        output._backward = _backward
        return output


    def __neg__(self):
        """
        Return the negation of this value.
            -x = x * (-1)
        """
        return self * -1


    def __sub__(self, other):
        """
        Subtract another value.
            x - y = x + (-y)
        """
        return self + (-other)


    def __radd__(self, other):
        """
        Support addition when Value appears on the right side.
            2 + Value(3)
        """
        return self + other


    def __rmul__(self, other):
        """
        Support multiplication when Value appears on the right side.
            2 * Value(3)
        """
        return self * other


    def __rsub__(self, other):
        """
        Support reverse subtraction.
            5 - Value(2)
        """
        return other + (-self)


    def __pow__(self, other):
        """
        Raise this value to a scalar power.
            output = self ** other

        Backpropagation uses:
            d(x^n)/dx = n * x^(n-1)
        """
        output = Value(
            data=self.data ** other, 
            children=(self,), 
            op=f"**{other}"
            )

        def _backward():
            self.grad += other * (self.data ** (other - 1)) * output.grad

        output._backward = _backward
        return output


    def __truediv__(self, other):
        """
        Divide by another value.
            x / y = x * (y ** -1)

        Reuses multiplication and power operations so no
        additional gradient logic is required.
        """
        if isinstance(other, Value):
            return self * (other ** -1)
        else:
            return self * (Value(other) ** -1)


    def relu(self):
        """
        Apply the ReLU activation function.
            ReLU(x) = max(0, x)

        During backpropagation:
            gradient = 1 if output > 0 else 0
        """
        output = Value(
            data=max(0, self.data),
            children=(self,), 
            op="relu"
            )

        def _backward():
            self.grad += (1.0 if output.data > 0 else 0.0) * output.grad

        output._backward = _backward
        return output


    def backward(self):
        """
        Compute gradients for all nodes in the computation graph.

        Performs:
        1. Topological sorting of the graph.
        2. Seeds the output gradient with 1.0.
        3. Traverses the graph in reverse topological order.
        4. Calls each node's stored backward function.

        After execution, every node's `grad` contains:
            d(output) / d(node)
        """
        topo = []
        visited = set()


        def build_topo(v):
            """
            Recursively build a topological ordering of nodes.
            """
            if v not in visited:
                visited.add(v)
                for child in v._prev:
                    build_topo(child)
                topo.append(v)

        build_topo(self)

        self.grad = 1.0

        for v in reversed(topo):
            v._backward()


    def exp(self):
        """
        Compute the exponential of this value.
            output = e^x

        Creates a new node representing the exponential function.

        During backpropagation, the derivative is:
            d(e^x)/dx = e^x

        Therefore:
            self.grad += output.data * output.grad
        """
        import math

        e = math.exp(self.data)
        output = Value(
            data=e,
            children=(self,),
            op="exp"
        )

        def _backward():
            self.grad += e * output.grad

        output._backward = _backward

        return output


    def log(self):
        """
        Compute the natural logarithm of this value.
            output = ln(x)

        Creates a new node representing the natural logarithm.

        During backpropagation, the derivative is:
            d(ln(x))/dx = 1/x

        Therefore:
            self.grad += (1 / self.data) * output.grad

        Note:
            The input value must be greater than zero.
        """
        import math

        output = Value(
            data=math.log(self.data),
            children=(self,),
            op="log"
        )

        def _backward():
            self.grad += (1.0 / self.data) * output.grad

        output._backward = _backward

        return output


    def tanh(self):
        """
        Apply the hyperbolic tangent activation function.
            output = tanh(x)

        The tanh function squashes values into the range [-1, 1]
        and is commonly used as an activation function in neural
        networks.

        During backpropagation, the derivative is:
            d(tanh(x))/dx = 1 - tanh²(x)

        Therefore:
            self.grad += (1 - output.data²) * output.grad
        """
        import math

        t = math.tanh(self.data)
        output = Value(
            data=t,
            children=(self,),
            op="tanh"
        )

        def _backward():
            self.grad += (1 - t**2) * output.grad

        output._backward = _backward

        return output
